### PR TITLE
Update pixi to 0.29.0

### PR DESCRIPTION
**Pull request by abey79**
### What

☝🏻 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7349?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7349?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7349)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Review by teh-cmc — APPROVED** [review]
But `@rerun-bot full-check` first please :grimacing:

**Comment by abey79** [comment]
@rerun-bot full-check

**Comment by abey79** [comment]
> But `@rerun-bot full-check` first please 😬

Good call!

**Comment by abey79** [comment]
It appears the compiler crash on CI is triggered by a mere `pixi update`. Not even the 0.25.0 -> 0.28.2 version bump.

**Comment by abey79** [comment]
Drafting this. I'm gonna need help to debug that weird crash. In the meantime, I'll revert to 0.25. `pixi self-update --version X.Y.Z` is your friend.

**Pull request closed without merging**
