### PR TITLE
Build all cpp binaries of test_wheels ci job in the `wheel-test-min` environment

### PR DESCRIPTION
**Pull request by Wumpf**
### What

Similar to https://github.com/rerun-io/rerun/pull/6911
May fix Windows issues or at least make it easier to diagnose

### Checklist
* [x]  pass main ci

- [PR Build Summary](https://build.rerun.io/pr/7009)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Wumpf** [comment]
@rerun-bot full-check

**Comment by Wumpf** [comment]
this didn't work!
https://github.com/rerun-io/rerun/actions/runs/10144399377/job/28048333277

**Comment by Wumpf** [comment]
something is still wrong
https://github.com/rerun-io/rerun/actions/runs/10145079802/job/28050625909

**Comment by Wumpf** [comment]
@rerun-bot full-check

**Comment by Wumpf** [comment]
@rerun-bot full-check

**Comment by Wumpf** [comment]
@rerun-bot full-check

**Review by jleibs — APPROVED** [review]

**Comment by jleibs** [comment]
I assume the issue with deploying docs is unrelated to anything changed in this PR

**Pull request merged**
