### PR TITLE
Make default notebook widget size smaller and configurable

### PR DESCRIPTION
**Pull request by jprochazk**
### What

- Part of https://github.com/rerun-io/rerun/issues/2289

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6827?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6827?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6827)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Wumpf** [comment]
not sure if that's what we want? The original ticket called for hyper intelligent (😉) sizing where we do stuff like detecting that an incoming image has a certain size.
No idea what a good size is for a widget in a notebook, why is this one better than the previous?

**Comment by jprochazk** [comment]
I misunderstood. This is just the first part of the issue, then. It's a better default size because it's smaller, with a 6.4 / 4.8 aspect ratio.

We can dynamically size the viewer as well, by updating its style. We can do that at any level (in viewer, in web-viewer JS, in widget JS, in `notebook.py`), but I'm not sure if we actually want to do that. 🤔

**Comment by jleibs** [comment]
It could be nice if the defaults were something the user could set once as a global instead of needing to override on every call you notebook_show.

**Comment by jprochazk** [comment]
> It could be nice if the defaults were something the user could set once as a global instead of needing to override on every call you notebook_show.

What would that look like? I don't know what would be idiomatic in Python, at least the following would be possible:

```py
# top-level function
from rerun.notebook import set_default_size
set_default_size(width=640, height=480)
```

```py
# static method
from rerun.notebook import Viewer
Viewer.set_default_size(width=640, height=480)
```

```py
# "static" property
from rerun.notebook import Viewer
Viewer.size = (640, 840)
```

**Comment by jleibs** [comment]
>  I don't know what would be idiomatic in Python, at least the following would be possible:

@abey79 do you have any thoughts on this?

I find the top-level function design:
```
from rerun.notebook import set_default_size
set_default_size(width=640, height=480)
```
to be the most straight-forward to think about.

**Comment by jprochazk** [comment]
Alright, I added `rerun.notebook.set_default_size`

**Review by jleibs — APPROVED** [review]

**Pull request merged**
