### PR TITLE
Fix file dialogs inside docker containers, improve file dialogs on web

### PR DESCRIPTION
**Pull request by Tuntenfisch**
Fixes rfd file-dialogs not opening up inside Docker containers by bumping the rfd version to 0.14.1 which includes a zenity fallback that works inside Docker containers. See https://github.com/rerun-io/rerun/issues/6794 for more info.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6795?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6795?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [ ] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6795)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Tuntenfisch** [comment]
@rerun-bot full-check

**Comment by emilk** [comment]
Unfortunately this leads to a lot of duplicated dependencies, as you can see by running `cargo deny check`. Usually this can be fixed by strategically updating other dependencies with `cargo update -p $CRATE`, where `$CRATE` can be deduced from the output of `cargo deny`

**Comment by Tuntenfisch** [comment]
> Unfortunately this leads to a lot of duplicated dependencies, as you can see by running `cargo deny check`. Usually this can be fixed by strategically updating other dependencies with `cargo update -p $CRATE`, where `$CRATE` can be deduced from the output of `cargo deny`

I think the main problem is that rfd bumped its ashpd version from 0.6 to 0.8 in https://github.com/PolyMeilex/rfd/commit/a88718eba75a70ee24753b3fa02e08f56b21670b which in turn now requires zbus version 4.0. Sadly I couldn't find a way to reconcile the duplicate zbus dependency. But I'm also not really familar with Rust as whoe, maybe I'm just too dumb.

**Comment by emilk** [comment]
No ETA on the `winit` update unfortunately. It is likely another 2 months before it makes its way to Rerun.

We could consider living with the duplicated dependencies, but I'm not a big fan of the increased compilation times that will result in.

**Comment by Tuntenfisch** [comment]
> No ETA on the `winit` update unfortunately. It is likely another 2 months before it makes its way to Rerun.
> 
> We could consider living with the duplicated dependencies, but I'm not a big fan of the increased compilation times that will result in.
> 
> 
> 
> 

No worries, maybe I can figure out a way to get rfd 0.12 with xdg-portal backend working inside my docker container after all.

**Comment by emilk** [comment]
I wonder if this PR solves
* https://github.com/rerun-io/rerun/issues/7138

**Comment by emilk** [comment]
an update of winit has now landed on `main`, so this is unblocked

**Comment by Wumpf** [comment]
looks like accesskit didn't get updated on egui - the zbus dependency hasn't improved when merging, resetting cargo.lock to main and building

**Comment by Wumpf** [comment]
> I wonder if this PR solves https://github.com/rerun-io/rerun/issues/7138

It does!
image
Still looks bad, but it's a looooot better!

**Comment by Wumpf** [comment]
The problem with access kit holding on to an old version unfortuantely persists

```
    = zvariant_derive v3.15.1
      └── zvariant v3.15.1
          ├── accesskit_atspi_common v0.9.0
          │   └── accesskit_unix v0.12.0
          │       └── accesskit_winit v0.22.0
          │           └── egui-winit v0.29.1
          │               └── eframe v0.29.1
```

Given that this update _also_ makes our save dialogs a lot better on the web, we surely can do some effort to fix the situation in accesskit @emilk ?

**Comment by emilk** [comment]
The latest `accesskit_atspi_common` uses `zvariant` 0.4: https://crates.io/crates/accesskit_atspi_common/0.9.3/dependencies

**Comment by Wumpf** [comment]
> A single duplicate of zvariant shouldn't block us though imho

well, then I'll add the necessary exception!

**Comment by Wumpf** [comment]
tried for a while, but it's a bit of a mess. There's other packages that are on 3.x.y zbus whereas other have moved on to 4.x.y.
Added cargo deny exception for this and did overall cleanup of deny exceptions

**Comment by Wumpf** [comment]
> Still looks bad, but it's a looooot better!

keeping the file dialog issue open since the confusing `Ok` button is still there

**Comment by emilk** [comment]
I'll tackle this in a new PR, together with a bunch of other cargo updates

**Comment by emilk** [comment]
* Blocked by https://github.com/Smithay/wayland-rs/issues/767

**Pull request closed without merging**
