### PR TITLE
Fix logged obb being displayed with half of the requested size

### PR DESCRIPTION
**Pull request by BenjaminDev**
### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
Fixing #1701
minimal test script
```
import rerun as rr

rr.spawn()
rr.log_obb("world/obb", [1, 2, 3], [0, 0, 0], None, color=[255, 0, 0])

expected_corners = [[d0, d1, d2] for d0 in (-1, 1) for d1 in (-2, 2) for d2 in (-3, 3)]
rr.log_points("world/corners", positions=expected_corners, colors=[0, 255, 0])
```
Output showing `oob` with correct verticies.

Untitled

If this is a suitable fix I'll add tests and polish. This is my first rerun contribution - I hope this finds a home. Thanks for the great tool - I've had a lot of fun using it.

### CODE REVIEW

**Review by Wumpf — CHANGES_REQUESTED** [review]
Glad you like using rerun and thank you so much for your contribution!!

There's sadly two problems with that solution though:

* it doesn't preserve the data in the viewer - i.e. when you inspect the data in the viewer you should be able to see exactly what was logged
* it doesn't solve the issue for the Rust (and future) APIs

To fix that we need to go a bit deeper and check what the internal store actually "thinks" it has: https://github.com/rerun-io/rerun/blob/main/crates/re_log_types/src/component_types/bbox.rs#L11
So looks like the store too thinks this should be half-sizes, confirming that the python API did the right thing.

So it seems the actual issue is when we gather the data to send it off to the renderer, so somewhere in here https://github.com/rerun-io/rerun/blob/main/crates/re_viewer/src/ui/view_spatial/scene/scene_part/boxes3d.rs (or actually the next step, in the renderer itself!)
If digging further is too much for you right now that's ok, I can make sure we prioritize this ticket (but I'd ofc very happy if you could chase this down 😄 )

**Comment by BenjaminDev** [comment]
Ah! I see. I'm keen, I'll take a closer look.

**Comment by BenjaminDev** [comment]
I hope this is a more suitable fix. As far as I can see the `scale` used in `let transform: Affine3A` must be "full_size". 

Unless we wanted to modify `add_box_outline` which would force other callers (seems to only be `RenderDepthClouds::draw`) to adjust their `scale`.

Concretely, I am pointing to something like (as an alternative):
```
-             transform.transform_point3(glam::vec3(-0.5, -0.5, -0.5)),
+            transform.transform_point3(glam::vec3(-1.0, -1.0, -1.0)),
...
```

Here is a small `data.rrd` file to reproduce. Load with current build see output similar to #1701 (shows bug). Load using this fix and see corrected behaviour. Ideally, I'd like to pop a test in somewhere (might need a pointer to where I should add this).
[data.rrd.zip](https://github.com/rerun-io/rerun/files/11128714/data.rrd.zip)

Thanks for the inputs here :)

**Review by Wumpf — APPROVED** [review]
ah I see, thanks for walking the last meters/mile there. Hmm got me pondering if fix in re_renderer and patching up of the remaining callsites would be better, but `Add box outlines from a unit cube` (as the outline method is documented) doesn't sound too bad, so let's not make this tiny thing _even_ more complicated 😅 

I wish I had a good answer on how to test this automatically, but I fear this is one of those things for which we'd need to introduce image-comparision-integration tests which we don't have yet 🤔. So let's take it as is

**Pull request merged**
