### PR TITLE
Move from instant -> web_time

### PR DESCRIPTION
**Pull request by jleibs**
### What
`instant` has at least one issue affecting us:
- https://github.com/sebcrozet/instant/issues/49
It also hasn't been updated in 18 months.

`web-time`: https://github.com/daxpedda/web-time appears to achieve the same goals, but is under active development and notably doesn't have the bug that `instant` had.

This replaces all usage of `instance` with `web_time`.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [ ] I've included a screenshot or gif (if applicable)

PR Build Summary: https://build.rerun.io/pr/2093

### CODE REVIEW

**Review by emilk — APPROVED** [review]
Nice!

Let's also forbid `instant` in `scripts/clippy_wasm/clippy.toml` under `disallowed-types`.

We could also add it to the `[bans]` list in `deny.toml`… but banning `instant` from all our dependencies may be taking it a bit too far

**Comment by emilk** [comment]
Oh, and make sure you test it on the web!

**Comment by jleibs** [comment]
Turns out there does appear to be a regression...  if you open a web-viewer in a hidden tab and allow enough time to pass (3 to 4 seconds?) then when changing to that tab we don't have any content for the spatial views:
image

Seems like we end up in a state where maybe an unknown time is ends up selected or something goes weird with forwarding playing of time.

There's a [known issue](https://github.com/daxpedda/web-time#note) listed in the repo, so I'm wondering if this is related.
> Currently a known bug is affecting browsers on operating system other then Windows. This bug prevents [Instant](https://doc.rust-lang.org/std/time/struct.Instant.html) from continuing to tick when the context is asleep. This doesn't necessarily conflict with Rusts requirements of [Instant](https://doc.rust-lang.org/std/time/struct.Instant.html), but might still be unexpected.

**Comment by jleibs** [comment]
The above issue appears likely to have been caused by: https://github.com/rerun-io/rerun/pull/2103

**Comment by emilk** [comment]
The issue was fixed by #2106 so I think this PR is good-to-go

**Pull request merged**
