### PR TITLE
Lower logo resolution to avoid aliasing on low-dpi screens

### PR DESCRIPTION
**Pull request by Wumpf**
### What

Has now the same vertical resolution as the R menu icon

---
Before on low-dpi (windows):
before

After on low-dpi (windows):
after

---

Before on low-dpi (mac):
image

After on low-dpi (mac):
after

---

Before on high-dpi (mac):
image

After on high-dpi (mac):
image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/{{ pr.number }}) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/{{ pr.number }})
- [Docs preview](https://rerun.io/preview/{{ "pr:%s"|format(pr.branch)|encode_uri_component }}/docs)
- [Examples preview](https://rerun.io/preview/{{ "pr:%s"|format(pr.branch)|encode_uri_component }}/examples)

### CODE REVIEW

**Comment by Wumpf** [comment]
actually. wait a second, this is cut off now to the right a little bit 🤦

**Comment by Wumpf** [comment]
fixed.

**Review by jleibs — APPROVED** [review]
Seems reasonable enough, though I don't fully understand why we need to use an image here instead of a font.

**Comment by Wumpf** [comment]
This thing started out as a font and looked pretty bad - no recognizability

**Pull request merged**
