### PR TITLE
Fix `main` build

### PR DESCRIPTION
**Pull request by emilk**
### What
Fix main build

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)

- [PR Build Summary](https://build.rerun.io/pr/7977)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by emilk** [comment]
@rerun-bot full-check

**Comment by emilk** [comment]
Nightly build underway: https://github.com/rerun-io/rerun/actions/runs/11641555623

**Comment by emilk** [comment]
@rerun-bot full-check

**Comment by emilk** [comment]
Nightly build: https://github.com/rerun-io/rerun/actions/runs/11641686053

**Review by abey79 — APPROVED** [review]

**Pull request merged**
