### PR TITLE
Run snapshot tests everywhere but render/compare only on mac

### PR DESCRIPTION
**Pull request by abey79**
### Related

- Related to #8245 

### What

Run snapshot tests everywhere but render/compare only on mac

### CODE REVIEW

**Comment by abey79** [comment]
@rerun-bot full-test

**Comment by nikolausWest** [comment]
What is the workflow then for generating a new snapshot if you're not on Mac? Is it run CI, manually download the right artifact, check it in, push, run CI again?

**Comment by abey79** [comment]
> What is the workflow then for generating a new snapshot if you're not on Mac? Is it run CI, manually download the right artifact, check it in, push, run CI again?

Well I'm not sure we can even recover the artefact from CI now, we'd need to add that. You _could_ generate a reference snapshot locally by temporarily removing the mac-only flag. The snapshot will likely have slight differences, but I believe the comparison allows for that.

Anyways, all of this is very painful, so we basically need #8245. I'm adding it to next cycle, chances are we can sort it out in a time-boxed pairing session with @Wumpf.

**Comment by lucasmerlin** [comment]
> Well I'm not sure we can even recover the artefact from CI now, we'd need to add that.

Should be quite simple to add this: 
https://github.com/emilk/egui/blob/master/.github/workflows/rust.yml#L247-L253

**Review by emilk — APPROVED** [review]

**Pull request merged**
