### PR TITLE
Merge rust scripts into `re_dev_tools` crate

### LINKED ISSUE #5889: Join our Rust "scripts" crates into one
We (well, @jprochazk) have started porting more and more `.sh` and `.py` scripts to Rust, and so far I think it has been a win. However, so far each such "Rust script" has become its own separate crate, which I think is the wrong direction:

* It requires many files (crate folder, `Cargo.toml`, `src` folder, `main.rs`, maybe a `README.md`)
* It makes it harder to add a new quick command (a lot of boilerplate setting up the above files)
* It adds more binaries (https://github.com/rerun-io/rerun/issues/4623)

So, I think we should consider an xtask-esque approach, where a single Rust binary multiplexes out into different Rust "scripts", so that each script is just a file added to the same crate.

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #5889

Puts a bunch of tooling under a new extensible home.

```
pixi run dev-tools --help
✨ Pixi task (default): cargo run -q --locked -p re_dev_tools -- --help
Usage: re_dev_tools <command> [<args>]

Various development tools for Rerun.

Options:
  --help            display usage information

Commands:
  build-examples    Build examples and their manifest.
  build-web-viewer  Build the web-viewer.
  search-index      Meilisearch indexer and REPL
```

Intentionally left out `re_types_builder` since it's fairly big on its own.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/5972?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/5972?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5972)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Wumpf** [comment]
@rerun-bot full-check

**Review by jprochazk — APPROVED** [review]

**Comment by jprochazk** [comment]
There does seem to be a build failure though: https://github.com/rerun-io/rerun/actions/runs/8689791623/job/23828496345

**Comment by Wumpf** [comment]
@rerun-bot full-check

**Comment by Wumpf** [comment]
still red

**Pull request merged**
