### PR TITLE
pixi: Add missing feature "cpp" to "wheel-test" environment

### PR DESCRIPTION
**Pull request by emilk**
### What
Should fix red main

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the 
* [x] I've checked that https://github.com/rerun-io/rerun/actions/runs/9871678286 is green

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by emilk** [comment]
@rerun-bot full-check

**Comment by emilk** [comment]
@rerun-bot full-check

**Comment by emilk** [comment]
I'm merging this in the interest of unblocking other PRs and making `main` green again

**Comment by jleibs** [comment]
Can you explain why `wheel-test` needs a dep on the cpp feature? What was the problem that this was trying to fix?

**Pull request merged**
