### PR TITLE
Switch to Vimeo for paper visualizations

### LINKED ISSUE #3138: Improve way of hosting / embedding videos
Currently we use YouTube to host the videos in the blog and examples, however, YouTube's embedding feature is quite limited:
- on repeat the UI pops up (looks especially poor for short videos)
- repeat is not seamless, but requires buffering every time
- sometimes not all embedded videos load (requiring to refresh the page)
- low quality by default (or depending on account settings I presume)

Hosting on vimeo might be one alternative that seems more feature-rich when it comes to embedding videos, but might require a subscription. Relevant links: [Autoplay and loop embedded videos](https://help.vimeo.com/hc/en-us/articles/12426486963857-Autoplay-and-loop-embedded-videos), [How to embed background and chromeless videos](https://help.vimeo.com/hc/en-us/articles/12426285089681) 
Second one says you need a subscription to disable controls / background, but it worked without for me as well.

### PR DESCRIPTION
**Pull request by roym899**
### What

Replaces all Youtube links with Vimeo.

Closes #3138.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3344) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/3344)
- [Docs preview](https://rerun.io/preview/3aac6f27f94a9519049e6eca41f755ba2b42e2d6/docs) 
- [Examples preview](https://rerun.io/preview/3aac6f27f94a9519049e6eca41f755ba2b42e2d6/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Comment by nikolausWest** [comment]
Ping @martenbjork: perhaps a quick update to landing could make vimeo as easy to use as youtube?

**Comment by martenbjork** [comment]
> Ping @martenbjork: perhaps a quick update to landing could make vimeo as easy to use as youtube?

@nikolausWest Yeah, I'll get on that today at 11 CET 🚀

**Comment by martenbjork** [comment]
Looks like the website already supports Vimeo embeds out of the box ☺️ https://github.com/rerun-io/landing/blob/main/src/components/Markdown/Markdown.tsx#L129

I tested it locally with a standard vimeo page url and it worked great: `https://vimeo.com/865326948`

**Comment by roym899** [comment]
@martenbjork I also tried this, however, out-of-the-box the styling is off (especially for videos with aspect ratios closer to 1:1) and the options such as autoplay can't be applied.

You can see it in the preview of this PR. For the last video on [this page](https://www.rerun.io/preview/2e657e5c007ebba9ab0a5f0404eafd229351bb81/examples/paper-visualizations/differentiable_blocks_world) I added a few different options for embedding the video. With just the URL, we get the white margins, and the rounded corners will be on the white, not the actual video. Also it seems like vimeo player options such as background, autoplay can't be applied this way.

I think the third option is what we want here styling-wise, i.e., maximum height for the video, rounded corners applying to the video, not the margin.

[Here](https://github.com/rerun-io/rerun/blob/2e657e5c007ebba9ab0a5f0404eafd229351bb81/examples/python/differentiable_blocks_world/README.md?plain=1#L35-L41) are the relevant lines of code.

**Comment by roym899** [comment]
Looks much better, some issues remaining though:
- instead of black letter box (background isn't fully black either), we can also get transparent by setting `color-scheme:none;` on the surrounding div
- more importantly videos with ratios closer to 1:1 will take the full available width, making them too big in comparison to other videos. I think we should limit the height a video can take. Current
wide With `max-height:22rem`:
Screenshot from 2023-09-19 15-46-51

**Comment by nikolausWest** [comment]
ping @martenbjork

**Comment by roym899** [comment]
@martenbjork I added all the videos but it seems like the ratio argument is cut of. For example, I specified it as 10000:6835 based on vimeos 68.35%. But it becomes 10000/6 in the CSS.

**Comment by martenbjork** [comment]
de12f571-72a4-4a85-a92b-ff2c8f81ce59_text

I made a mistake in the regex. It's been fixed now. It also supports fractional ratios, like 1/1.5. Let me know if there are any more issues!

**Comment by roym899** [comment]
Great, looks like it all works :tada:
I still think the videos are too big compared to the text (at least when viewing on desktop, looks pretty good on mobile), but I think this PR is done.

**Review by nikolausWest — APPROVED** [review]
Great!

**Pull request merged**
