### PR TITLE
Enable dataframe streaming across Python FFI

### PR DESCRIPTION
**Pull request by teh-cmc**
Title.

Just trying _not_ to bury the actual important thing into the previous mammoth PR :melting_face: 

* DNM: requires #7934 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7935?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7935?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7935)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by teh-cmc** [comment]
@rerun-bot full-check

**Comment by teh-cmc** [comment]
@rerun-bot full-check

**Review by emilk — APPROVED** [review]
If the PR only removes code, but the code it removes are `/*` `*/` pairs… is it removing code, or adding it? 🧘

**Comment by teh-cmc** [comment]
If a forest falls but also a tree does it sound, yes?

**Pull request merged**
