### PR TITLE
Fix auto properties no longer being applied for legacy properties (`EntityProperties`)

### LINKED ISSUE #6175: Heuristics for depth image size broken, causing arkit scenes to be unusable
Must have gone in very recently.

Can't see the mesh anymore because it's dwarfed by the depth cloud
image

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #6175

This regressed in #6164. Decided not to roll back things (which would have been hard) but instead reimplement how these properties are passed through and make their role more obvious.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6190?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6190?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6190)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by teh-cmc** [comment]
This highlighted a mishandled edge-case introduced in https://github.com/rerun-io/rerun/pull/6157 caused by the use of `TimeInt::MIN` instead of `TimeInt::STATIC`.

Rebased on `main` and fixed the issue directly here.

**Comment by teh-cmc** [comment]
Things now work as expected:
image

But I don't get why the UI says the `Backproject meter` prop is `1.0`. Shouldn't that be `1000.0`?

**Comment by Wumpf** [comment]
oh good catch. more bugs.

**Review by jleibs — APPROVED** [review]
Makes sense. Appreciate the rename since it makes it easier to delete this once the legacy props are gone.

**Pull request merged**
