### PR TITLE
Update the UI colors to use our (blueish) ramp instead of pure greys

### PR DESCRIPTION
**Pull request by abey79**
### What

This PR changes most shades of grey used in the UI to those defined in the design token color ramp, which has a slight blueish taint. This reduces a lot of cold/warm contrast we used to have, for a more uniform look.

Before:

image

After:

image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7075?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7075?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7075)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by abey79** [comment]
@gavrelina

Tab bar title color is currently 175.
Bottom bar color is currently 150.

Bottom bar stroke color was pure grey(47) but I just changed it to 250, like separators. Its this one:
image


We need to fix tooltip background as well. Currently it's grey(35):

image


The top bar is grey(20). I assume it should be changed too.
image

**Comment by gavrelina** [comment]
@abey79 so following up your comment above, a few changes:

1. "Tab bar title color is currently 175." => change to **200** 
2. "Bottom bar color is currently 150." => double checking — you mean the bar of the timeline section, right? and with it the most of the timeline panel as well. We leave it as is! because we are imitating a bit of the depth with elevating the bottom part of the UI. 
3. "tooltip grey(35)" => to **250** (it's lighter than most of our backgrounds, because we want a tooltip to have a feeling of elevation as well!). This also shall be apply for the Rerun menu background color. 
3a. There is a grey entity on hover (in my screenshot it has old grey, in your screenshot I see you have changed that already) => to double check it, should be **325**
Screenshot 2024-08-07 at 14 10 47

4. "The top bar is grey(20)" => it has some funky alignments, let's remove the extra grey shade from it, keep it 100 or actually use **Alias.Color.Surface.Default.value.** 

5. There is also a hover on the tabs and/or rr logo that is grey. Change it to **325** (like 3a). I mean these:
Screenshot 2024-08-07 at 14 19 43

**Comment by abey79** [comment]
Updated as per your comment—looks much nicer!

> you mean the bar of the timeline section, right?

Yes!

**Review by gavrelina — APPROVED** [review]
So nice!

**Pull request merged**
