### PR TITLE
CI: Retry `linkinator`

### PR DESCRIPTION
**Pull request by jprochazk**
### Checklist
* [ ] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [ ] I've included a screenshot or gif (if applicable)

PR Build Summary: https://build.rerun.io/pr/2299

Docs preview: https://rerun.io/preview/5aa6ab9/docs

### CODE REVIEW

**Review by emilk — APPROVED** [review]
nice, that was easy!

**Comment by emilk** [comment]
…well, except it doesn't work :P

**Comment by jprochazk** [comment]
Sorry, should've turned this into a draft. I'm in the process of forking `linkinator-action` and adding retry option directly into it

**Comment by jprochazk** [comment]
Okay, now it hopefully will retry a few times before failing. Of course that requires an actual failure and despite retrying the workflow a few times, it hasn't failed yet, so we'll just have to wait and see. I did also submit the changes as a PR to upstream https://github.com/JustinBeckwith/linkinator-action/pull/157

**Review by emilk — APPROVED** [review]
Let's try it I guess :)

**Pull request merged**
