### PR TITLE
WIP: albedo textures as color maps + integration into depth clouds

### PR DESCRIPTION
**Pull request by teh-cmc**
Very wip, but we're close... very close :hot_face: 

TODO: probably go through the image cache for the albedo; there's just too many edge cases... also give a good reason to take care of #1462 

https://user-images.githubusercontent.com/2910679/222545682-05936fd3-e660-4977-baab-98a8289f347f.mp4

### CODE REVIEW

**Comment by nikolausWest** [comment]
@teh-cmc: what's blocking this now?

**Comment by zrezke** [comment]
@teh-cmc this is very nice, what's the status on this?

**Comment by teh-cmc** [comment]
> @teh-cmc this is very nice, what's the status on this?

This should be waaay easier to do now, with all the recent work that has landed with regards to texture uploads and GPU colormapping.

I'll do so in another PR once I have some time. Keeping this draft open so I don't forget.

**Comment by teh-cmc** [comment]
- #2702

**Pull request closed without merging**
