### PR TITLE
Remove the "+" icon from the "Add SV/Container" modal and close on click

### PR DESCRIPTION
**Pull request by abey79**
### What

This PR introduces two minor tweaks to the "Add Space View or Container" modal:
- remove the big "+" button
- close the modal on click

image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4927/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4927/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4927/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4927)
- [Docs preview](https://rerun.io/preview/46b823d22815129b69a2506ab91389d7b994200c/docs) 
- [Examples preview](https://rerun.io/preview/46b823d22815129b69a2506ab91389d7b994200c/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Comment by nikolausWest** [comment]
Nice! One more small one (mentioned on the same ticket as these): select the newly created container or space view

**Comment by abey79** [comment]
> Nice! One more small one (mentioned on the same ticket as these):
> 
> * [ ]  select the newly created container or space view
> 
> Brownie points:
> 
> * [ ]  Preview with the same (viz as when dragging) where the thing will be created (when the modal is open)
> 
> Note: both of these can go in other PRs at another time but thought I'd mention them here since this PR doesn't reference an issue

I'll do the selecting one soon, but in a different PR because it touches some other places.

As for the preview one, I've added to the todo list. This one is a bit more evolve and requires some work to support a "temporary/preview viewport" in our code. I'll add that topic to the current cycle.

**Comment by nikolausWest** [comment]
> As for the preview one, I've added to the todo list. This one is a bit more evolve and requires some work to support a "temporary/preview viewport" in our code. I'll add that topic to the current cycle.

I should have clarified that I primarily meant previewing in the blueprint tree but I think it's a good idea to preview everywhere in a unified manner

**Comment by abey79** [comment]
> > As for the preview one, I've added to the todo list. This one is a bit more evolve and requires some work to support a "temporary/preview viewport" in our code. I'll add that topic to the current cycle.
> 
> I should have clarified that I primarily meant previewing in the blueprint tree but I think it's a good idea to preview everywhere in a unified manner

Oh ok—useful clarification 👍🏻

**Review by emilk — APPROVED** [review]

**Pull request merged**
