### PR TITLE
Add `cargo semver-checks` as a step in the patch release process

### PR DESCRIPTION
**Pull request by emilk**
[`cargo semver-checks`](https://github.com/obi1kenobi/cargo-semver-checks) will check that we haven't introduced any semver breaking changes

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5186/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5186/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5186/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5186)
- [Docs preview](https://rerun.io/preview/10d8b8604c333395c2dd8dd6569276377442d37f/docs) 
- [Examples preview](https://rerun.io/preview/10d8b8604c333395c2dd8dd6569276377442d37f/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Review by teh-cmc — APPROVED** [review]

**Comment by obi1kenobi** [comment]
👋 Hey! I'm the maintainer of `cargo-semver-checks`, thanks for adopting it! Please give me a ping if you run into any issues with it.

I also noticed you're about to ship a Python SDK. Any chance you might be interested in a Python breaking change linter as well?

I saw you have an impending release date, so I don't mind waiting if it's not a good time right now :) Good luck with the launch!

**Comment by emilk** [comment]
Hi @obi1kenobi and thanks for `cargo semver-checks`. I tried it for the first time the other day when making a patch release for egui, and it was really nice. I'm looking forward using it more going forward.

Yes, a similar tool for our Python API would be great!

**Comment by obi1kenobi** [comment]
Thanks! Out of curiosity, are there other lints you'd like to be able to run beyond just scanning for breaking changes?

For example things like:
- don't allow functions to accept kwargs positionally (so enforce `def func(a, *, kwarg=None)` instead of `def func(a, kwarg=None)`)
- every `__init__.py` should have an `__all__` attribute
- the docs must have documentation for every class and function that's public, where "public" is customizable — e.g. "in a non-underscored module and in its `__all__` attribute"

I'm looking into how we can streamline coding and new-hire onboarding via automated checks. We all enforce a lot of stuff solely via code review, and that's wasteful of time and energy.

**Comment by obi1kenobi** [comment]
Awesome! The linter I'm building is called `pepperlint` and it can already catch ~20 flavors of breaking changes. It can even catch some breaking changes that happen inside dynamically executed code such as this:
```python
def __getattr__(name):
    if name == "example_func":
        from .inner import example_func
        return example_func
    # Imagine these lines are accidentally deleted. Oops!
    # This would break anyone importing `MyClass` from here.
    #
    # elif name == "MyClass":
    #     from .inner import MyClass
    #     return MyClass
    else:
        raise ImportError(f"Item {name} does not exist.")
```

In addition to the built-in lints, it can support adding user-defined lints as well — they would use the same declarative query syntax as `cargo-semver-checks`.

I'd love to show you a demo, and learn about how you'd prefer to use it (GitHub Action? IDE integration? just a CLI tool?) and any other requirements or nice-to-haves you might think of.

Who on your team would be the best folks for me to chat with next week?

**Pull request merged**
