### PR TITLE
Always-on AV1 in `--release`; opt-in to nasm-optimizations

### PR DESCRIPTION
**Pull request by emilk**
### What
Even without `nasm`, it is pretty fast.

I also added a warning to the user that they can get more performance by enabling the `nasm` feature.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7661?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7661?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7661)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by emilk** [comment]
The `nasm` feature is on by default for our `pip` package build, so they won't see a warning

**Review by Wumpf — APPROVED** [review]
title a bit misleading. It's still off on debug

**Comment by Wumpf** [comment]
how are we building the standalone executables that we upload to GH? Those should also get that feature flag

**Comment by emilk** [comment]
> how are we building the standalone executables that we upload to GH? Those should also get that feature flag

Good question. I'v created a separate issue for it:

* https://github.com/rerun-io/rerun/issues/7669

**Pull request merged**
