### PR TITLE
Allow logging individual components directly (Impl `AsComponents` for all `ObjectKind::Component`)

### PR DESCRIPTION
**Pull request by oxkitsune**
### What

This implements `AsComponents` for all `Component`s, which makes the rust api slightly more ergonomic and makes this possible:

```rs
rec.log_static("my_points", &rerun::Color::from_rgb(128, 128, 128))?;
```

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7756?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7756?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7756)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by teh-cmc** [comment]
Nice!

I wonder if we can avoid generating actual code at all here though: have you tried looking into something along the lines of `impl<C: Component> AsComponents for C`?

**Comment by oxkitsune** [comment]
> I wonder if we can avoid generating actual code at all here though: have you tried looking into something along the lines of impl<C: Component> AsComponents for C?

Yea that is possible! I originally thought of this, but then got excited by the codegen and wanted to mess with that haha.
I'm not sure where that trait impl belongs, but I've just put it right below the definition of `AsComponents`

**Comment by Wumpf** [comment]
oh my. Just tried it. So easy and so much better with this o_o
took the liberty to push in a small doc update related to this.

Strangely, I wasn't able to find any snippet or example that profits from this directly. Looks like we always dogged this in those so far :/. Or maybe I'm missing something.

**Review by Wumpf — APPROVED** [review]

**Comment by Wumpf** [comment]
the python ci failure can be ignored, that's a known issue with non-maintainer-ci. But the Rust issues are proper compile errors in the tests

**Comment by oxkitsune** [comment]
Oh damn, I'll take a look!

Our use case involves logging static colours for specific entities, to avoid having to log them each time and hopefully save some bandwidth 🤞

**Comment by Wumpf** [comment]
Note for posterity: As demonstrated by the test fixes this is "slightly" api breaking, so we better don't put this into a patch release

**Pull request merged**
