### PR TITLE
Change the "slow-down-camera" modifier to Alt on non-Mac

### LINKED ISSUE #1867: Using WASD+EQ with Ctrl Modifier results in program exit & save file.
It seems that using the WASDEQ keys, for moving around the 3d view, the speed can be modified via Ctrl|Shift|Alt.  This is nice, however it appears to clash with application level keyboard shortcuts: Ctrl-Q, and Ctrl-S.

**To Reproduce**
1. Press Ctrl-Q or Ctrl-S, expecting fine movement in the Y-Up, or Z-Back direction.
2. The application quits, or pops up a save dialog.

**Expected behavior**
1. Maybe remove the application level key bindings. Needing to quit the application, and save, come up alot less frequently than fine-level control of camera, for certain data sets.
2. Have Shift + WASDEQ be the fine-level movement, instead of control. Perhaps even removing Control entirely. Currently Shift moves _very_ fast, for a dataset which is 70m+ in the X+Z directions, the dataset flies out of the view very easily.

**Your goals**
Move around the dataset to get a view from a particular point, needing quite fine level control over movement.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.10

### PR DESCRIPTION
**Pull request by h3mosphere**
This Fixes #1867. Setting Alt as the slowdown behaviour for the camera movement. Note, that this also sets it to alt for wasm architecture, let me know if you wish for an extra check for wasm (and leave it as alt).

Thanks.

### Checklist
* [X] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [X] I've included a screenshot or gif (if applicable)
* [X] I have tested [demo.rerun.io](https://demo.rerun.io/pr/{{ pr.number }}) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/{{ pr.number }})
- [Docs preview](https://rerun.io/preview/{{ "pr:%s"|format(pr.branch)|encode_uri_component }}/docs)
- [Examples preview](https://rerun.io/preview/{{ "pr:%s"|format(pr.branch)|encode_uri_component }}/examples)
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Comment by emilk** [comment]
Thanks for the PR!

It is desirable to keep the same shortcuts natively as on the browser on the same computer. To that end we would need to change the compile-time switch in this PR to a runtime switch. You can use [`ui.ctx().os()`](https://docs.rs/egui/latest/egui/struct.Context.html#method.os) to get the current OS (even on web). `SLOW_DOWN_3D_MODIFIER` would thus need to be turned into a function taking `egui::os::OperatingSystem` as an argument.

**Comment by h3mosphere** [comment]
OK, that was easy enough.

There are some new problems with both Alt-E, and Ctrl-E being captured by the browser, but native is probably more important (it is to me anyway), and this problem exists regardless (current behaviour is broken with Ctrl-E in chrome on linux).

This also updates the help text, in which the displayed modifiers were reversed to what they actually are.

**Review by emilk — APPROVED** [review]

**Comment by Wumpf** [comment]
Anything missing before we get this in, meaning getting it out of draft?

**Comment by emilk** [comment]
`cargo cranky` passes locally - LGTM!

**Pull request merged**
