### PR TITLE
Normalise Python typing syntax to 3.8+

### PR DESCRIPTION
**Pull request by abey79**
### What

This TBD PR attempts to normalise all python code to idiomatic, Python 3.8 compatible, syntax, primarily around typing ((through `from __future__ import annotations`), but also other aspect covered by PyUpgrade such as f-strings, etc.

This has wide ranging impact on the Python code, so could potentially mess-up existing PR.

**TBD**:
- remove `set -e` from py-lint (annoying when errors are triggered by out-of-PR files, but impacts CI)
  - My take: leave as is. It's annoying when lints dont pass (as was the case as of ~ 370e16fc56ba0daecef13b7380d5cc6b6387091c), but this shouldn't be the norm.
- `from __future__ import annotations` was ["manually"](https://github.com/asottile/pyupgrade/issues/618) added, so it's not done by `py-format` nor checked by `py-lint`.
  - My take: ok as is, but let's make it a concession to always add `from __future__ import annotations` in python files.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [ ] ~~I've included a screenshot or gif (if applicable)~~

PR Build Summary: https://build.rerun.io/pr/2361

Docs preview: https://rerun.io/preview/de126a6/docs
Examples preview: https://rerun.io/preview/de126a6/examples

### CODE REVIEW

**Review by emilk — APPROVED** [review]
OMG, the type annotations are so much nicer with `|`!

We could consider checking that each `.py` file contains `from __future__ import annotations` in our own `lint.py` if we want to.

**Comment by abey79** [comment]
Actually, Ruff appears to have something like that already: https://github.com/astral-sh/ruff/pull/1762

I'll try and add that.

**Comment by teh-cmc** [comment]
> Actually, Ruff appears to have something like that already: [astral-sh/ruff#1762](https://github.com/astral-sh/ruff/pull/1762)
> 
> I'll try and add that.

This can wait for a follow-up imo; I'd rather we merge this before monday kicks in, this is a ticking merge conflict bomb :grimacing:

**Comment by abey79** [comment]
Good point

**Pull request merged**
