### PR TITLE
Fix ui for color fallback showing the wrong value

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Part of https://github.com/rerun-io/rerun/issues/6595

All color fallback value juggling is now more or less forced to go through a (typed) fallback provider.
This way, the ui can query the fallback as well, even when it's not in use.

The "structure" of the helix demo has an orang'ish fallback but is set grey via store:
image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6703?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6703?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6703)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by teh-cmc** [comment]
Unrelated to this PR but this highlights the pre-existing fact that colors derived from hashes somehow still differ on native vs. web :sob: 

Native:
image

Web:
image

I could have sworn we already had an issue for this but i can't find it so here's a new one:
- https://github.com/rerun-io/rerun/issues/6706

**Comment by abey79** [comment]
Isn't the fallback dependent on the both the entity _and the instance index_? It seems so from this example, and, if so, the UI is somewhat confusing:

image

**Comment by Wumpf** [comment]
Color is never sourced from instance index. The problem in this example is that the colors are sourced from the annotation context. And annotation context is not handled by the ui at all. Huge mess that I'd rather not tackle in this cycle, but maybe we should talk about it

**Comment by abey79** [comment]
> Color is never sourced from instance index. The problem in this example is that the colors are sourced from the annotation context. And annotation context is not handled by the ui at all. Huge mess that I'd rather not tackle in this cycle, but maybe we should talk about it

Oh right—forgot about that. Yeah let's not address that for now, but defo something worthing figuring how to solve. One short term action might be to blanket-add a note about this in the tooltips of all potentially concerned components (regardless for whether an annotation context is logged for not).

**Review by abey79 — APPROVED** [review]
lgtm

**Pull request merged**
