### PR TITLE
New screenshots and thumbnails for the examples

### PR DESCRIPTION
**Pull request by abey79**
### What

This PR updates the examples' READMEs with new screenshots and adds the `thumbnail:` entry to their front matter.

This uses #2411 and highlighted some bugs with it, to be fixed in a follow-up PR.

TODO:
- [x] deal with signed_distance_fields
- [x] deal with detect_and_track_objects
- [x] deal with ros_node

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a WHOLE LOT of screenshots in the PR

PR Build Summary: https://build.rerun.io/pr/2440

Docs preview: https://rerun.io/preview/b2d508b/docs
Examples preview: https://rerun.io/preview/b2d508b/examples

### CODE REVIEW

**Review by teh-cmc — APPROVED** [review]
Looks fantastic on my end for both desktop and mobile (I find it looks even better on mobile in fact).

Some random feedback, nothing blocking:
- Navigating the examples on github now looks kinda weird with the front matter turning into a huge weirdly formatted and cropped in half table:
image
Can't we hide that stuff behind a comment or something?
- I find it very hard to see what's going on in the right hand side of the colmap screenshot (is it the angle? not enough visible history?):
image
If I wasn't so familiar with it i'm not sure I'd have any idea what I'm looking at. Might just be me.
- Similarly, I have a hard time making out the tensor view used in the SDK example:
image
Not sure whether that's due to the settings used in the view (need to tweak colormapping etc) or just the mesh itself which doesn't lend itself too well to the exercise (the lamp pole mesh makes for a way clearer demo in my experience).
- The DICOM example could really use some color:
image
Maybe add a second view with a turbo map applied?

**Comment by abey79** [comment]
- Maybe @jprochazk can comment on the front matter stuff. It's likely only going to get worse as we add more metadata there.
- On the car viz: that point cloud is rather messy. I tried my best but it'll just never be super nice/clear on a frozen screenshot
- @Wumpf feeling like revisiting that SDF example?
- Dicom: I'll take a look

**Comment by jprochazk** [comment]
Yeah, I had the same concern regarding the frontmatter rendering in the initial PR (https://github.com/rerun-io/rerun/pull/2309). I wish GH would just hide it. But we can change it to something like
```
<!--[[metadata]]
title: API Demo
python: https://github.com/rerun-io/rerun/tree/latest/examples/python/api_demo/main.py
rust: https://github.com/rerun-io/rerun/tree/latest/examples/rust/api_demo/src/main.rs
thumbnail: https://static.rerun.io/d41179fb380bc6bdeda950d7d69e3c457ff295e9_api_demo_480w.png
-->

...
```

Another option is to move it to a different file. Either way making the required changes to landing would not be too much work

**Comment by Wumpf** [comment]
> Similarly, I have a hard time making out the shape in the tensor view used in the SDF example:

oof I tried hard already to extract anything out of that is visible, switched through different color maps and found that one the most visible one
@teh-cmc to you also get that many areas of broken depth in that example? I get it on pretty much any mesh

**Comment by teh-cmc** [comment]
> > Similarly, I have a hard time making out the shape in the tensor view used in the SDF example:
> 
> oof I tried hard already to extract anything out of that is visible, switched through different color maps and found that one the most visible one @teh-cmc to you also get that many areas of broken depth in that example? I get it on pretty much any mesh, but for the lamppole it felt worse that's why I picked that mesh instead

I've never seen these artifacts before in my life actually :smile: 

Here's an example lamp pole with some turbo map on my end:
image

**Comment by teh-cmc** [comment]
And the kind of silly ideas I had in mind for a more colorful DICOM:
image

**Comment by abey79** [comment]
> And the kind of silly ideas I had in mind for a more colorful DICOM:
> image

That is cool! Didn't realise all those options existed.

**Comment by abey79** [comment]
> Yeah, I had the same concern regarding the frontmatter rendering in the initial PR (#2309). I wish GH would just hide it. But we can change it to something like
> 
> ```
> 
> 
> ...
> ```
> 
> Another option is to move it to a different file. Either way making the required changes to landing would not be too much work

The sad part about this is that the front matter format is sort of standard and benefits from tooling checks, etc.

**Comment by Wumpf** [comment]
> I've never seen these artifacts before in my life actually 😄

I suppose this runs into some GL bugs on Mac (or GL being GL uses some less defined cases)

**Comment by Wumpf** [comment]
@teh-cmc this is what I get for the lamppole...
image

**Comment by abey79** [comment]
Merging this. We'll improve the SDF example later on.

**Pull request merged**
