### PR TITLE
Update egui and wgpu

### LINKED ISSUE #3973: Update to wgpu 0.18
Not out as of writing (expected on 25th Oct). Let's try it out before hand, report issues and update for our 0.11 release

### PR DESCRIPTION
**Pull request by Wumpf**
### What

* Fixes #3973
* Depends on https://github.com/emilk/egui/pull/3505

### Test Matrix
Make sure to click through a few examples to cover at least points, lines and meshes. (Arkit is a good one!)

* [ ] Test window-related stuff on Linux:
  * [ ] check that resizing the window works
  * [ ] that the icon shows
  * [ ] that file->open works
  * [ ] that the DPI is sane and persisted on restart
  * [ ] Look for any other weird regressions

* [x] Mac
    * [x] native
    * [x] WebGL Firefox
    * [x] WebGL Chrome
    * [x] WebGL Safari
    * [x] (optional) WebGPU Chrome
* [x] Linux
    * [x] native
    * [x] WebGL Firefox
    * [x] WebGL Chrome
* [x] Windows
    * [x] native
    * [x] WebGL Firefox
    * [x] WebGL Chrome
    * [x] WebGL Edge
    * [ ] (optional) WebGPU Chrome
* [x] Merge egui PR

### Checklist
* [x] https://github.com/emilk/egui/pull/3505 has been merged
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/4111) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4111)
- [Docs preview](https://rerun.io/preview/73199e5727c18529cdbd2dd3956af17204403f96/docs) 
- [Examples preview](https://rerun.io/preview/73199e5727c18529cdbd2dd3956af17204403f96/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Comment by Wumpf** [comment]
(don't merge tag for not depending on an egui master version)

**Review by jleibs — APPROVED** [review]
Changes all look straightforward

**Comment by emilk** [comment]
I suggest we wait with this until we are ready for the next egui release, containing the new multi-viewport PR and probably a winit update: https://github.com/emilk/egui/milestone/2

**Comment by emilk** [comment]
Testing:

* [ ] Linux
* [ ] macOS
* [ ] Windows

* check that resizing the window works
* that the icon shows
* that file->open works
* that the DPI is sane and persisted on restart

**Comment by emilk** [comment]
Ok, everything is updated and ready

**Comment by abey79** [comment]
Should we avoid merging before this one is fixed?

https://github.com/emilk/egui/issues/3633

**Comment by teh-cmc** [comment]
Breaks window resizing and frequently crashes on wgpu errors on X11 (XWayland) and Wayland

**Comment by emilk** [comment]
@teh-cmc Does applying [this fix](https://github.com/emilk/egui/issues/3628#issuecomment-1827943346) to the egui repository fix your problems?

**Comment by teh-cmc** [comment]
> @teh-cmc Does [emilk/egui#3643](https://github.com/emilk/egui/pull/3643) fix your problems? i.e. patching `egui-winit` to `e6815ae1ea212732683e3f05be7cadf17d228a9a`

yep, fixed

**Comment by emilk** [comment]
Clement says it is good now. I'm gonna give WebGPU a whirl, then merge it.

**Pull request merged**
