### PR TITLE
Fix various links in rust, python and toml files

### LINKED ISSUE #5925: Better link checker on CI (`linkinator` and `lychee` misses important things)
* https://github.com/rerun-io/rerun/pull/5923

Another example:
https://docs.rs/rerun/latest/rerun/trait.AsComponents.html links to https://github.com/rerun-io/rerun/blob/latest/examples/rust/custom_data/src/main.rs which is 404 - I've intentionally not fixed this link yet so we can check that the fixed link checker catches it

This makes me worried that we have a lot of broken links.

We need to either fix `linkinator`, or switch to a better tool.

### PR DESCRIPTION
**Pull request by Wumpf**
### What

Code files are now included in link checking.

* Fixes #5925

Some issues encountered:
* globs don't respect exclude_files which makes working with this locally harder https://github.com/lycheeverse/lychee/issues/1405
* can't specify extensions / correct files aren't picked up automatically https://github.com/lycheeverse/lychee/issues/410

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/5986?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/5986?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5986)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Wumpf** [comment]
Link checker now picks up 5711 links
https://github.com/rerun-io/rerun/actions/runs/8703457384/job/23869674908

Before it picked up 4533 links
https://github.com/rerun-io/rerun/actions/runs/8701752080/job/23864360265

**Comment by jprochazk** [comment]
Does it have a way to report which links it checked so we can be sure that it checks what `linkinator` missed?

**Comment by Wumpf** [comment]
> Does it have a way to report which links it checked so we can be sure that it checks what linkinator missed?

yes, I documented that in lychee.toml: you pass in `--dump-link` and it tells you.
Or do you mean we should have something on ci as well as an artifact?

**Review by emilk — APPROVED** [review]
nice!

**Comment by jprochazk** [comment]
Yes, I meant on CI. Linkinator would always report the full list of links it checked, would be nice to have that instead of just the number of links.

**Comment by Wumpf** [comment]
I'll have a look!

**Comment by Wumpf** [comment]
@jprochazk done! :) https://github.com/rerun-io/rerun/actions/runs/8704483825/job/23872854352

**Pull request merged**
