### PR TITLE
Make the recordings panel resizable

### PR DESCRIPTION
**Pull request by emilk**
### What
* Closes https://github.com/rerun-io/rerun/issues/3421

resizable-panel

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7180?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7180?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7180)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Wumpf** [comment]
Not a huge issue but feels a bit weird when there's not much content in there.

https://github.com/user-attachments/assets/3f197a1d-442c-4f12-8e14-b07fc82a1a54

**Comment by abey79** [comment]
There is also a glitch when resizing the time panel.

https://github.com/user-attachments/assets/c30e3b15-11a5-4db1-9eff-2fff90984dcb

**Comment by emilk** [comment]
Both fixed

**Review by teh-cmc — APPROVED** [review]
:pray:

**Comment by abey79** [comment]
This introduced several messy UI elements:
- https://github.com/rerun-io/rerun/issues/7197

**Pull request merged**
