### PR TITLE
Use `log_static()` for constant data in DNA example.

### PR DESCRIPTION
**Pull request by kpreid**
### What

Just a tiny little thing that was bugging me: the DNA example now uses `log_static()` for all the non-animated data logged at the beginning. This gives better results when viewing with a time range query — otherwise the `left`, `right`, and `scaffolding` always disappear if the time range doesn’t include the beginning of the recording.

Here is the new appearance with a 0.5 second time range; previously, only the gray points would be visible:

Screenshot

### Checklist
* [X] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [X] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7701?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7701?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [X] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [X] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [X] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7701)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by teh-cmc** [comment]
Nice -- I've been meaning to do that for a while.

`log_static` is deprecated though, lemme fix that.

**Review by teh-cmc — CHANGES_REQUESTED** [review]
I want it too. But if we do it we need to do it on all three DNA examples (python, cpp, rust)!

**Comment by teh-cmc** [comment]
(marking as draft to relax the review queue til then)

**Comment by Wumpf** [comment]
taking this over, I too want this too :)

**Comment by Wumpf** [comment]
✅  tested C++ & Python manually (you never know, weirder things have broken...)

**Review by zehiko — APPROVED** [review]

**Comment by Wumpf** [comment]
ci:
* known rust failure, fix is up
* C++ runner running out of space. okay. 🤦

**Pull request merged**
