### PR TITLE
Officially deprecate support for python 3.8

### PR DESCRIPTION
**Pull request by jleibs**
### What
- Resolves: https://github.com/rerun-io/rerun/issues/7830

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7933?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7933?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [x] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/7933)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Review by Wumpf — APPROVED** [review]
neat!
haven't tried whether the warning triggers myself, but I trust you did :)

**Review by abey79 — APPROVED** [review]
Well done. Just to be sure, do users have a means to silence those warning? They could be very annoying for a (still legitimate) use under 3.8. (Or do we think this barely happens anyways?)

**Comment by jleibs** [comment]
Python actually silences deprecation warnings by default in most user-facing contexts, which is a bit annoying and practically reduces the chances it will be seen by the users in practice, but that's the policy and I'm not going to fight it or workaround it.

Regardless, this is the "most right" way to handle it. If you enable deprecation warnings in your project config you'll see it, otherwise it won't be visible.

**Comment by jleibs** [comment]
Also worth noting that when we drop support, the new wheels will list their incompatibility so people installing will just get an older version or a pypi error if they try to install an explicit version in a 3.8 context.

**Pull request merged**
