### PR TITLE
Add  ml_depth_pro example

### PR DESCRIPTION
**Pull request by oxkitsune**
### What

https://github.com/user-attachments/assets/b7adac6a-60e4-4a1c-a27b-34006b87713a

This adds an external example for visualizing DepthPro using the new video logging api

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/7832)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Review by Wumpf — APPROVED** [review]
nice! Description lgtm, maybe a bit on the short side 🤷 Is there maybe a link to the paper that could be included as well?

I tried it with this old classic
image
For some reason it ended up only doing three frames hum.

**Comment by Wumpf** [comment]
looks like `pixi run lint-rerun` is unhappy. probably needs some `NOLINT` comments (there's now also `BEGIN_NOLINT` and `END_NOLINT`)

**Comment by oxkitsune** [comment]
Sure, I will add some more details to the description.

As for the error, it might have logged a text log for the error, I suspect it's HF limits. 

I run a forward pass for each frame separately which might eat the ZeroGPU budget up too fast

**Comment by oxkitsune** [comment]
Getting this for each frame while running it:
image 😢 

will look into batching it

**Comment by oxkitsune** [comment]
Lints pass, and batched inference works when I tested it locally on a `4090`. I am out of ZeroGPU quota so I can't test it on HF for now

**Pull request merged**
