### PR TITLE
Make scroll-to-zoom a lot more responsive in 3D views

### PR DESCRIPTION
**Pull request by emilk**
### What
Switch from linear interpolation to exponential.

Now 90% of the scroll delta is applied within 0.1 seconds. This is long enough to feel smooth, but short enough to feel responsive.

This feels great on my Mac

* Closes https://github.com/rerun-io/rerun/issues/4664

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4668/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4668/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4668/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4668)
- [Docs preview](https://rerun.io/preview/6b5b07e83b24740b8b916fd9fc69ab86b54acef9/docs) 
- [Examples preview](https://rerun.io/preview/6b5b07e83b24740b8b916fd9fc69ab86b54acef9/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Review by Wumpf — APPROVED** [review]
tried on Mac @ web with touchpad, mouse wheel stepped, mouse wheel smooth (logitech stuff) and all modes feel great with this fix! <3

**Comment by Wumpf** [comment]
@ankeanke gave it a spin (pun intended) on Linux @ Firefox and confirmed it behaving nicely

**Comment by jleibs** [comment]
I still find the size of a scroll step to be unreasonably large on linux

This is one wheel click forward/backward:

https://github.com/rerun-io/rerun/assets/3312232/0ffd790a-31de-4645-87c0-bf4ca3a78147

**Comment by Wumpf** [comment]
size of scroll step hasn't changed in this PR. I suppose we need to do something more clever scene dependent and maybe clamp large scroll steps on some mouse wheels? The annoying thing is that what we get from a mouse wheel is "number of text lines to scroll up or down"

**Comment by jleibs** [comment]
> size of scroll step hasn't changed in this PR

Yeah -- it hasn't gotten worse. I'm just saying any improvements from this PR are dwarfed by the fact that it's always been terrible. I thought there was an old issue for this but I can't find it now.

**Pull request merged**
