### PR TITLE
reopen for #4717 adding a cpp_example to visualize openMVG::sfm_data exported from openMVG structure from motion pipeline

### PR DESCRIPTION
**Pull request by khshmt**
### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4782/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4782/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4782/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4782)
- [Docs preview](https://rerun.io/preview/b7b02b12209c4d59e871f8af47c736d2d38c9fd9/docs) 
- [Examples preview](https://rerun.io/preview/b7b02b12209c4d59e871f8af47c736d2d38c9fd9/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Comment by Wumpf** [comment]
Sorry for not replying on this for so long! As discussed on the previous PR I'd like to either put this into a separate repository that we link to or - even better - put it directly into OpenMVG "next to" the Rerun Python example there. Again, we'd refer to that example then from the docs. @pmoulon are you interested in taking this (or a similar) example in on OpenMVG or would you rather not take that on?

**Comment by pmoulon** [comment]
@Wumpf yes we should move this. I was working on integrating rerun c++ to OpenMVG officially (see some videos I shared on LinkedIn). This new PR is showing that we should do deliver the implementation in OpenMVG and make a nice example for rerun. I will try to move from the code I got + the PR that @khshmt sent to OpenMVG and come back here when done. Thank you guys for supporting this!

**Comment by teh-cmc** [comment]
I'll draft this in the meantime to reduce the noise in the review queue.

**Comment by Wumpf** [comment]
OpenMVG has a sample now, we so can close this
https://github.com/openMVG/openMVG/pull/2284

But we should still link to both the Python and the C++ examples!
* https://github.com/rerun-io/rerun/issues/4960

**Pull request closed without merging**
