### PR TITLE
Use explicit cast on forwarding in an attempt to make asan happier

### PR DESCRIPTION
**Pull request by Wumpf**
### What

Hitting some spurious asan issues on ci: Some Linux runs end up spamming `AddressSanitizer:DEADLYSIGNAL` indefinitely with no additional information.
This started with:
* #5544

so this PR tries to wiggle that piece of code a bit by making it more obvious what's happening both to human and machine (? - jury still out on that).

Defined a `FwdType` alias to keep things shorter

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5557/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5557/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5557/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5557)
- [Docs preview](https://rerun.io/preview/71edf5b9fede23b929239a8b8f5f1b5d70792f09/docs) 
- [Examples preview](https://rerun.io/preview/71edf5b9fede23b929239a8b8f5f1b5d70792f09/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Comment by Wumpf** [comment]
did not work so far https://github.com/rerun-io/rerun/actions/runs/8326523953/job/22782380753?pr=5557

**Comment by Wumpf** [comment]
Looks like explicitly disabling worked. Triggering two more manual runs to confirm.

The other changes are a net improvement I think, so keeping them

**Comment by Wumpf** [comment]
extra runs:
* https://github.com/rerun-io/rerun/actions/runs/8327256543

**Comment by Wumpf** [comment]
disabling ASAN for the changed functions doesn't get us any further it seems.

**Comment by Wumpf** [comment]
another attempt:
* https://github.com/rerun-io/rerun/actions/runs/8328547083
* https://github.com/rerun-io/rerun/actions/runs/8328545313

**Review by teh-cmc — APPROVED** [review]

**Pull request closed without merging**
