### PR TITLE
Make on TextLogLevel PascalCase (instead of SCREAMING CASE) to avoid clashes with preprocessor defines

### PR DESCRIPTION
**Pull request by Wumpf**
### What

Considered also just using lower case on these (nobody would do `#define debug`, ... RIGHT?). But they are _enum - like_ constants so all-caps felt appropriate.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/4152) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4152)
- [Docs preview](https://rerun.io/preview/ff8b29947f85102e649b7cb2ed651228888d3bf1/docs) 
- [Examples preview](https://rerun.io/preview/ff8b29947f85102e649b7cb2ed651228888d3bf1/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Review by abey79 — APPROVED** [review]
That was my preferred choice, so I'm gonna approve this ;)

**Comment by emilk** [comment]
Alternative: use `PascalCase` for constants in C++. See https://github.com/rerun-io/rerun/issues/4151#issuecomment-1795314675

**Comment by Wumpf** [comment]
Discussed this a bit more on internal Slack: there's some risk that `Debug` is a define as well, but we'll take that.
Our enums that are emitted for arrow union types already follow this convention so we can stick with that everywhere now

**Review by abey79 — APPROVED** [review]
lgtm

**Pull request merged**
