### PR TITLE
Fix flickering of orbit camera indicator

### LINKED ISSUE #2201: Flickering 3D frame when moving camera
**Describe the annoyance**
The 3D frame that appears when moving the camera flickers.

This seems to happen only in the prerelease right now.

**Video**

https://github.com/rerun-io/rerun/assets/9785832/2a534dc1-b49d-42c5-92db-e3a218003711

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - `rerun-sdk 0.6.0a0+2023.5.24.043b7a3`

### PR DESCRIPTION
**Pull request by Wumpf**
and make it disappear more smoothly by collapsing inwards

Fixes #2201
* #2201

Stressing it a bit by holding the mouse still and moving just when it disappears again:
https://github.com/rerun-io/rerun/assets/1220815/5d53dd1b-a7bb-4846-8ad5-fd422fe7ed2d
But I think this works out now fine enough.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/2746) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/2746)
- [Docs preview](https://rerun.io/preview/pr%3Aandreas%2Ffix-flickering-orbit-center/docs)
- [Examples preview](https://rerun.io/preview/pr%3Aandreas%2Ffix-flickering-orbit-center/examples)

### CODE REVIEW

**Review by teh-cmc — APPROVED** [review]
I actually love the smooth scaling-out-into-a-black-hole animation much more than an alpha fade haha.

Two minor nits:
- The delay between me releasing my mouse and the fade-out animation starting at all is unusually long (at least when testing on the web demo?)
- It feels a bit weird to me that we fade on the way out but just pop instantly on the way in... shouldn't we fade on the way in too?

**Comment by Wumpf** [comment]
good idea. I'll reduce the delay and make the animation go both ways!

**Comment by Wumpf** [comment]
also made it so that the thing doesn't disappear when mouse is pressed; found that a bit irritating when changing the camera, waiting am moment and then continuing.
Needed to keep the delay somewhat long because otherwise mouse wheel zoom looks bad quickly. Maybe shouldn't show it at all in those cases 🤔

**Comment by teh-cmc** [comment]
Love it. I'm inclined to remove it when zooming, it doesn't add anything in that case imo and is rather annoying.

**Pull request merged**
