### PR TITLE
Reorganize Selection Panel

### PR DESCRIPTION
**Pull request by emilk**
### What
* Closes https://github.com/rerun-io/rerun/issues/6615
* Part of https://github.com/rerun-io/rerun/issues/6075

Each section now only does one thing, with a good name to describe it, and in a good order.

image image

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6637?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/6637?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/6637)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Comment by Wumpf** [comment]
consensus so far (and what's noted down in the ticket) was to push visible/interactive all the way up to the top without its own section https://rerunio.slack.com/archives/C041NHU952S/p1718878768702219?thread_ts=1718822157.478409&cid=C041NHU952S
personally I think its own section is also fine, but `Entity properties` is not the right name for it. All of these things are properties of the selected entity

**Comment by Wumpf** [comment]
`View settings` also makes me pause a bit: we called it `View properties` so far, but maybe `settings` is actually better. But then we also have to change it in the docs, e.g. here https://rerun.io/docs/reference/types/views/spatial3d_view#properties

**Comment by Wumpf** [comment]
The separation line at the end of visible time range doesn't make sense to me. Is this a left over or intentional?
image

**Comment by Wumpf** [comment]
interesting bug: the arrows are not aligned
image
Likely unrelated to this PR

**Comment by Wumpf** [comment]
This tooltip isn't pretty being elongated as it is
image

**Review by Wumpf — COMMENTED** [review]
skimmed the code mostly only, lgtm. Above comments need addressing but doesn't need to be in here (need to note it down though if we don't do it right away)

**Comment by abey79** [comment]
I'm seeing some issues with that header:
1) it should force align itself on round pixels vertically, to avoid that thin gap
2) alignment bug with the + button

Both of these would be addressed by implementing it using listitem, but doing so would force an indent on the expended content (unless we add an indent-less version of `show_*` to list item).

Also, the final horizontal separator after Visible Time Range should be removed.


image

**Comment by abey79** [comment]
I'm not fully convinced by the new placement of the ?/Edit button here:

image

Ideally we'd have an "Edit" icon and something like this:

image

having the "?" up there would be useful in other places, such as the visualiser section.

**Comment by abey79** [comment]
There vertical spacing is still a bit all over the place. In this data section, the fact that the list items hover-highlight further show that there is a gap.


image
image

**Pull request merged**
