### PR TITLE
Add cyan to yellow colormap

### PR DESCRIPTION
**Pull request by rasmusgo**
### What

This PR adds a new colormap: cyan to yellow. The colormap is designed to work well for red-green colorblind people and make it easy to see the sign and magnitude of values in the range -1 to 1. It is dark and dull in the middle and bright and colorful at the ends.

image
This screenshot is from https://www.shadertoy.com/view/lfByRh.

image
This screenshot is from the signed distance field example. The normalization of values interferes with the colormap as it shifts the center of the colormap away from zero. It will become easier to use it to its full potential when range controls for colormaps are added. This problem is related to #6106 and #1510.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [ ] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7001?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/7001?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [ ] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [ ] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [ ] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/{{pr.number}})
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Review by Wumpf — APPROVED** [review]
Looking great!

Good as-is once @jleibs confirmed that this doesn't break our rectangle shader again on his Chrome Linux setup where we encountered issues before whenever that shader got directly or indirectly longer

**Review by jleibs — APPROVED** [review]
This appears to work for me on chrome/intel.

**Comment by Wumpf** [comment]
ci failure is a known issue with contributor ci

**Comment by emilk** [comment]
* I hope this won't awaken https://github.com/rerun-io/rerun/issues/3931 again 😬

**Comment by Wumpf** [comment]
That's what Jeremy's test was all about

**Comment by rasmusgo** [comment]
Centering the colormap around zero is now possible thanks to #7549! ❤️

**Pull request merged**
