### PR TITLE
Docs: fix broken links

### PR DESCRIPTION
**Pull request by teh-cmc**
Title.

* Related: #7887 

---

* [x] yes

### CODE REVIEW

**Comment by teh-cmc** [comment]
Remaining failures are third-parties, all good.

**Comment by teh-cmc** [comment]
Now the question is: do we consider fixing the links good enough, or do we really want to maintain a million redirect stubs instead?

**Review by Wumpf — APPROVED** [review]
I'd say it's good enough for all pages here!

**Comment by teh-cmc** [comment]
Change of plans: we'll fix the current batch of broken URLs with redirect stubs, and open an issue to decide how to handle these things in the future.

**Pull request closed without merging**
