### PR TITLE
Add support for Python 3.12

### LINKED ISSUE #3699: Support Python 3.12
Python 3.12.0 was recently released (Oct, 2nd) and we should support it.

This is currently blocked by `pyarrow` 3.12 wheel availability:
* https://github.com/apache/arrow/issues/37880

### PR DESCRIPTION
**Pull request by abey79**
### What

* Bumps arrow to 14.0.2
* Fixes #3699
* Relates to https://github.com/rerun-io/rerun/issues/2445

I added a bunch of fixes to `scripts/run_all.py`, which has a marked tendency to bit rot:
* https://github.com/rerun-io/rerun/issues/4710

Some workaround introduced to deal with PyTorch not 3.12 ready, see:
- https://github.com/rerun-io/rerun/issues/4704

TODO:
- [x] `nox -s tests-3.12` passing
- [x] `nox -s run_all-3.12 --save` passing
- [x] `nox -s roundtrips-3.12` passing
- [x] Solve this:
  ```
  ❯ pixi add pyarrow==14.0.0 
  × could not determine any available versions for pyarrow on linux-64. Either the package could not be found or version constraints on other dependencies result in a conflict.
  ╰─▶ Cannot solve the request because of: No candidates were found for pyarrow ==14.0.0.
  ```
- [x] Test won't pass until torch is updated for 3.12: https://github.com/pytorch/pytorch/issues/110436

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/4146) (if applicable)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4146)
- [Docs preview](https://rerun.io/preview/c0e892a228fcc83e9bef7faff1e17998926ffe52/docs) 
- [Examples preview](https://rerun.io/preview/c0e892a228fcc83e9bef7faff1e17998926ffe52/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

### CODE REVIEW

**Comment by genemerewether** [comment]
Hi, any plans to merge this or are you waiting for the pytorch test dep? thanks!

**Comment by abey79** [comment]
PyTorch is still not released for python 3.12 sadly, but apparently the nightly works. Maybe we could have test work by updating our `requirements_*.txt` with:

```
torch ; python_version < "3.12"
--pre --index-url https://download.pytorch.org/whl/nightly torch ; python_version >= "3.12"
```

**Comment by genemerewether** [comment]
> PyTorch is still not released for python 3.12 sadly, but apparently the nightly works. Maybe we could have test work by updating our `requirements_*.txt` with:
> 
> ```
> torch ; python_version < "3.12"
> --pre --index-url https://download.pytorch.org/whl/nightly torch ; python_version >= "3.12"
> ```

That would be great, if you're open to it. My env requires pyarrow >= 14 and I've been eagerly waiting to integrate rerun (having tested in a separate env)

**Comment by abey79** [comment]
I could get `nox -s tests-3.12` to pass by gating torch in `requirements_*.txt` and explicitly installing its nightly in `noxfile.py`.

**Review by jleibs — APPROVED** [review]

**Pull request merged**
