### PR TITLE
Use same pixi version on all of CI (0.20.0)

### PR DESCRIPTION
**Pull request by emilk**
### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)

- [PR Build Summary](https://build.rerun.io/pr/6088)
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

### CODE REVIEW

**Review by Wumpf — APPROVED** [review]
huh so those got missed on a recent update round?

**Review by teh-cmc — DISMISSED** [review]
This is going to happen again and again. We should use a GHA variable for this: https://github.com/rerun-io/rerun/settings/variables/actions

**Comment by emilk** [comment]
Nope, I seem to get a different pixi.lock than everyone else, because the CI hates my new pixi.lock

**Comment by jleibs** [comment]
> We should use a GHA variable for this

The one challenge with this is that it can't be updated atomically as part of a PR in conjunction with with pixi.toml / pixi.lock.  There may be future pixi versions that require this change so there will be a bit of an annoying dance to maneuver when that happens.

Could be worth seeing if there is a way to always seed global environment variables from a single config file at the root of the repo.

**Comment by Wumpf** [comment]
that's an alias @jleibs introduced yesterday. but why is it not found Oo.
Maybe just need to merge in main?

**Comment by emilk** [comment]
> This is going to happen again and again. We should use a GHA variable for this: https://github.com/rerun-io/rerun/settings/variables/actions

Sounds like a fun journey for another day

**Pull request merged**
