### PR TITLE
Finer plot aggregation

### PR DESCRIPTION
**Pull request by emilk**
### What
* Workaround for https://github.com/rerun-io/rerun/issues/4969

We would previously aggregate the plots over a time-window equal in width to a ui point.

The MinMax aggregator does a zig-zag between min and max, so this causes a very jagged look, especially on high-dpi screens.

With this PR, we switch to using a physical pixels as the default aggregation width, but for MinMax is is _half_ a pixel. This reduces the jaggedness, but does not completely remove it. It comes at a cost though of higher tessellation cost.

I have an idea for how we can throw rayon on the tessellation problem though.

## Before
Screenshot 2024-02-01 at 14 18 26

## After
Screenshot 2024-02-01 at 14 18 00

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/4998/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/4998/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/4998/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4998)
- [Docs preview](https://rerun.io/preview/17721aa538a03c890574d14795dce6502f8cc004/docs) 
- [Examples preview](https://rerun.io/preview/17721aa538a03c890574d14795dce6502f8cc004/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

### CODE REVIEW

**Comment by nikolausWest** [comment]
Worth checking the before and after performance on the plot-dashboard benchmark script for this one

**Review by teh-cmc — APPROVED** [review]
lgtm as long as the impact on a plot dashboard is negligible

**Comment by emilk** [comment]
Test-data:

```
just rs-plot-dashboard --num-plots 10 --num-series-per-plot 5 --num-points-per-series 5000 --freq 1000 --save big-plot.rrd
```
|   | tessellation ms  |
|---|---|
| main | 2.9 ms |
| This PR, serial tessellation | 4.5 ms |
| This PR, parallell tessellation | 2.4 ms |


Tessellation on `main`:  is around 2.9ms, and run 4.8ms
After this PR: with parallell tessellation OFF: 4.5ms

**Comment by emilk** [comment]
Yeah, I think I will roll this back to using full pixel width, thinking especially about retina screens on web.

**Pull request merged**
